---
- name: Download hangout
  get_url: url={{ hangout_url_deb }} dest={{hangout_tmp_deb}}
  tags: ["packages","hangout"]

- name: Install hangout for Debian
  apt: deb={{hangout_tmp_deb}}
  tags: ["packages","hangout"]
